version: "3.4"

services:
  postgres:
    container_name: express-postgres
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: ExpressPostgresDB
      POSTGRES_PASSWORD: postgres

volumes:
  postgres_data:
